In [1]:
import pandas as pd
import numpy as np

In [2]:
data_prepocessed = pd.read_csv('new_data.csv')
data_prepocessed.head(20)

Reason_1  Reason_2   Reason_3   Reason_4  Day of the Week  Month Value  \
0          0         0          0          1                1            7   
1          0         0          0          0                1            7   
2          0         0          0          1                2            7   
3          1         0          0          0                3            7   
4          0         0          0          1                3            7   
5          0         0          0          1                2           10   
6          0         0          0          1                4            7   
7          0         0          0          1                4            7   
8          0         0          1          0                6            6   
9          0         0          0          1                0            7   
10         1         0          0          0                0            7   
11         1         0          0          0                1            7   
12         1         0          0          0                2            7   
13         1         0          0          0                2            7   
14         0         0          0          1                2            7   
15         1         0          0          0                4            7   
16         0         0          0          1                4            7   
17         0         0          1          0                0            7   
18         1         0          0          0                3            7   
19         0         0          0          1                4            5   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      289                36   33                  239.554   
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   
15                     246                25   41                  239.554   
16                     179                51   38                  239.554   
17                     179                51   38                  239.554   
18                     189                29   33                  239.554   
19                     248                25   47                  205.917   

    Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                30          0         2     1                          4  
1                31          0         1     0                          0  
2                31          0         0     0                          2  
3                24          0         2     0                          4  
4                30          0         2     1                          2  
5                31          0         0     0                          2  
6                27          0         1     4                          8  
7                23          0         4     0                          4  
8                25          0         2  

In [3]:
data_prepocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_prepocessed['Absenteeism Time in Hours'] >data_prepocessed['Absenteeism Time in Hours'].median(),1,0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
targets.sum() /targets.shape[0]

0.45571428571428574

In [7]:
data_with_targets = data_prepocessed.drop(['Absenteeism Time in Hours','Daily Work Load Average','Distance to Work'],axis=1)

In [8]:
data_with_targets

Reason_1  Reason_2   Reason_3   Reason_4  Day of the Week  Month Value  \
0           0         0          0          1                1            7   
1           0         0          0          0                1            7   
2           0         0          0          1                2            7   
3           1         0          0          0                3            7   
4           0         0          0          1                3            7   
..        ...       ...        ...        ...              ...          ...   
695         1         0          0          0                2            5   
696         1         0          0          0                2            5   
697         1         0          0          0                3            5   
698         0         0          0          1                3            5   
699         0         0          0          1                3            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          2         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [9]:
data_with_targets.shape

(700, 12)

In [10]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2   Reason_3   Reason_4  Day of the Week  Month Value  \
0           0         0          0          1                1            7   
1           0         0          0          0                1            7   
2           0         0          0          1                2            7   
3           1         0          0          0                3            7   
4           0         0          0          1                3            7   
..        ...       ...        ...        ...              ...          ...   
695         1         0          0          0                2            5   
696         1         0          0          0                2            5   
697         1         0          0          0                3            5   
698         0         0          0          1                3            5   
699         0         0          0          1                3            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          2         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [11]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [12]:
unscaled_inputs

Reason_1  Reason_2   Reason_3   Reason_4  Day of the Week  Month Value  \
0           0         0          0          1                1            7   
1           0         0          0          0                1            7   
2           0         0          0          1                2            7   
3           1         0          0          0                3            7   
4           0         0          0          1                3            7   
..        ...       ...        ...        ...              ...          ...   
695         1         0          0          0                2            5   
696         1         0          0          0                2            5   
697         1         0          0          0                3            5   
698         0         0          0          1                3            5   
699         0         0          0          1                3            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  
0                       289   33               30          0         2  
1                       118   50               31          0         1  
2                       179   38               31          0         0  
3                       279   39               24          0         2  
4                       289   33               30          0         2  
..                      ...  ...              ...        ...       ...  
695                     179   40               22          1         2  
696                     225   28               24          0         1  
697                     330   28               25          1         0  
698                     235   32               25          2         0  
699                     291   40               25          0         1  

[700 rows x 11 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [14]:
# 標準偏差などの計算
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [15]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.76743118,
        -0.42368477,  0.88046927],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.42368477, -0.01928035],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.42368477, -0.91902997],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         1.07419067, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         2.57206611, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.42368477, -0.01928035]])

In [16]:
scaled_inputs .shape

(700, 11)

In [17]:
from sklearn.model_selection import train_test_split
# データを分割する

In [18]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ...,  1.23783558,
         -0.42368477,  0.88046927],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.42368477,  1.78021889],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.42368477, -0.01928035],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.42368477, -0.01928035],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.29702678,
         -0.42368477, -0.91902997],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.87898422,
         -0.42368477,  2.67996851]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.29702678,
         -0.42368477, -0.91902997],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.42368477,  0.88046927],
        [-0.57735027, -0.09298136,  3.17979734, ...,  0.76743118,
         -0.42368477,  0.88046927],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [19]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size=0.8)

In [20]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [21]:
print(x_test.shape,y_test.shape)
# 訓練:テスト＝3:1

(140, 11) (140,)


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [23]:
reg=LogisticRegression()

In [24]:
reg.fit(x_train,y_train)

LogisticRegression()

In [25]:
reg.score(x_train,y_train)
# 正確性の値

0.7714285714285715

In [26]:
model_outputs = reg.predict(x_train)

In [27]:
model_outputs
# x_trainのデータを元に検出した値

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,

In [28]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,

In [29]:
np.sum((model_outputs == y_train)/model_outputs.shape[0])

0.7714285714285715

In [30]:
reg.intercept_

array([-0.28129792])

In [31]:
reg.coef_

array([[ 2.00815157,  0.25781408,  1.39433791,  1.3000513 , -0.17326199,
         0.02233457,  0.51263316, -0.2308324 ,  0.35988286,  0.0303468 ,
         0.53767315]])

In [32]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', ' Reason_3', ' Reason_4',
       'Day of the Week', 'Month Value', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children'], dtype=object)

In [33]:
feature_name = unscaled_inputs.columns.values

In [34]:
summary_table = pd.DataFrame(columns =['Feature name'],data= feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.008152
1                 Reason_2     0.257814
2                 Reason_3     1.394338
3                 Reason_4     1.300051
4          Day of the Week    -0.173262
5              Month Value     0.022335
6   Transportation Expense     0.512633
7                      Age    -0.230832
8          Body Mass Index     0.359883
9                Education     0.030347
10                Children     0.537673

In [35]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.281298
1                 Reason_1     2.008152
2                 Reason_2     0.257814
3                 Reason_3     1.394338
4                 Reason_4     1.300051
5          Day of the Week    -0.173262
6              Month Value     0.022335
7   Transportation Expense     0.512633
8                      Age    -0.230832
9          Body Mass Index     0.359883
10               Education     0.030347
11                Children     0.537673

In [36]:
# 係数を出す(Coefficientが大きいと影響が大きい、Odds_ratioは要因がある場合に欠勤に対する割合)
summary_table['Odds_ratio'] =np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.281298    0.754803
1                 Reason_1     2.008152    7.449535
2                 Reason_2     0.257814    1.294098
3                 Reason_3     1.394338    4.032304
4                 Reason_4     1.300051    3.669485
5          Day of the Week    -0.173262    0.840917
6              Month Value     0.022335    1.022586
7   Transportation Expense     0.512633    1.669682
8                      Age    -0.230832    0.793873
9          Body Mass Index     0.359883    1.433162
10               Education     0.030347    1.030812
11                Children     0.537673    1.712019

In [37]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                 Reason_1     2.008152    7.449535
3                 Reason_3     1.394338    4.032304
4                 Reason_4     1.300051    3.669485
11                Children     0.537673    1.712019
7   Transportation Expense     0.512633    1.669682
9          Body Mass Index     0.359883    1.433162
2                 Reason_2     0.257814    1.294098
10               Education     0.030347    1.030812
6              Month Value     0.022335    1.022586
5          Day of the Week    -0.173262    0.840917
8                      Age    -0.230832    0.793873
0                Intercept    -0.281298    0.754803

In [38]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [39]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', ' Reason_3', ' Reason_4',
       'Day of the Week', 'Month Value', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children'], dtype=object)

In [40]:
columns_to_scale = [ 'Day of the Week', 'Month Value', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children']

In [41]:
absenteeism_scaler = CustomScaler(columns_to_scale)

TypeError: __init__() takes 1 positional argument but 4 were given

In [ ]:
absenteeism_scaler.fit(unscaled_inputs)

In [ ]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [ ]:
scaled_inputs

In [ ]:
# モデルのテスト
reg.score(x_test,y_test)

In [ ]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

In [ ]:
predicted_proba[:,1]

In [ ]:
import pickle

In [ ]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [ ]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)